from tests.dialects.test_dialect import Validator


class TestNuoDB(Validator):
    dialect = "nuodb"

    def test_ddl(self):
        self.validate_all("UPDATE teams SET wins = wins + 1 WHERE teamid IN ('COB', 'BOS', 'AND');")
        self.validate_all("DELETE FROM teams WHERE teamid IN ('COB', 'BOS', 'AND');")
        self.validate_all(
            "INSERT INTO hockey.hockey (number, name, position, team) VALUES (99, 'TOM JONES', 'Goalie', 'Bruins');"
        )
        self.validate_all(
            "CREATE TABLE employees(id INTEGER, first_name VARCHAR(50), last_name VARCHAR(50), salary DECIMAL(10, 2))",
            write={
                "nuodb": "CREATE TABLE employees (id INTEGER, first_name VARCHAR(50), last_name VARCHAR(50), salary DECIMAL(10, 2))",
                "mysql": "CREATE TABLE employees (id INT, first_name VARCHAR(50), last_name VARCHAR(50), salary DECIMAL(10, 2))",
                "postgres": "CREATE TABLE employees (id INT, first_name VARCHAR(50), last_name VARCHAR(50), salary DECIMAL(10, 2))",
                "tsql": "CREATE TABLE employees (id INTEGER, first_name VARCHAR(50), last_name VARCHAR(50), salary NUMERIC(10, 2))",
                "oracle": "CREATE TABLE employees (id NUMBER, first_name VARCHAR2(50), last_name VARCHAR2(50), salary NUMBER(10, 2))",
            },
        )

        self.validate_all(
            "CREATE DATABASE simpleDB",
            write={
                "nuodb": "CREATE SCHEMA simpleDB",
            },
        )

        self.validate_all(
            "ALTER TABLE employees ADD COLUMN hire_date DATE",
            write={
                "nuodb": "ALTER TABLE employees ADD COLUMN hire_date DATE",
            },
        )

    def test__auto_increment_to_generated_by_default(self):
        self.validate_all(
            "CREATE TABLE employees (id INT auto_increment, first_name VARCHAR(50), last_name VARCHAR(50), salary DECIMAL(10, 2))",
            write={
                "nuodb": "CREATE TABLE employees (id INTEGER GENERATED BY DEFAULT AS IDENTITY, first_name VARCHAR(50), last_name VARCHAR(50), salary DECIMAL(10, 2))"
            },
        )

    def test_parse_foreign_key_index(self):
        self.validate_all(
            "CREATE INDEX titles_emp_no ON titles (emp_no)",
            write={"nuodb": "CREATE INDEX titles_emp_no ON titles (emp_no)"},
        )
